# Generated by Django 4.2.19 on 2025-02-19 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.CharField(max_length=50)),
                ('product_MRP', models.CharField(max_length=50)),
                ('product_img', models.URLField()),
                ('product_rating', models.CharField(max_length=50)),
                ('total_customer_rating', models.IntegerField()),
                ('product_page_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_whatsapp', models.BooleanField(default=True)),
                ('use_sms', models.BooleanField(default=False)),
                ('use_email', models.BooleanField(default=True)),
                ('use_push', models.BooleanField(default=True)),
                ('use_in_app', models.BooleanField(default=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
