# Generated by Django 4.2.19 on 2025-02-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_daily_usage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_ordered_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_point',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
